services:
  bot:
    build:
      dockerfile: ./docker-build/app/Dockerfile_bot
      context: ./
    restart: unless-stopped
    container_name: checks_bot
    command: python3 main.py
    volumes:
      - shared-data:/app/shared
    environment:
      APP_CONFIG__DB__ECHO: 0
    ports:
      - "8002:8000"

  celery-1:
    build:
      context: ./
      dockerfile: ./docker-build/app/Dockerfile
    container_name: checks_celery
    command: celery -A app.celery.celery_app worker --pool=threads --loglevel=info -c 1
    volumes:
      - .:/app
      - shared-data:/app/shared
    working_dir:
      /app
    environment:
      - PYTHONPATH=/app/src
    restart: unless-stopped

  flower:
      build:
        context: .
        dockerfile: ./docker-build/app/Dockerfile_base
      container_name: checks_flower
      command: celery -A app.celery.celery_app flower --port=5555 \
        --basic_auth=${APP_CONFIG__FLOWER__USER}:${APP_CONFIG__FLOWER__PASSWORD}
      volumes:
        - .:/app
      working_dir: /app
      environment:
        PYTHONPATH: /app/src
      ports:
        - "8443:5555"
      restart: unless-stopped

volumes:
  shared-data:

networks:
  default:
    external:
      name: shared_network
