FROM python:3.13.3-slim-bookworm

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

# Устанавливаем Poetry
RUN pip install --upgrade pip wheel "poetry==2.1" setuptools

# Копируем файлы для зависимостей
COPY pyproject.toml poetry.lock ./

# Устанавливаем зависимости (без dev-зависимостей)
RUN poetry config virtualenvs.create false && \
    poetry install --no-dev --no-interaction --no-ansi

# Копируем остальные файлы проекта
COPY /src .

# Запускаем приложение
CMD ["uvicorn", "photo_server:app", "--host", "0.0.0.0", "--port", "8000"]