"""init

Revision ID: 5e1eb2164bac
Revises: 69427ccd51bf
Create Date: 2025-06-03 21:05:08.534017

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e1eb2164bac"
down_revision: Union[str, None] = "69427ccd51bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "receipt_items",
        "unit",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "receipt_items",
        "unit",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
    )
    # ### end Alembic commands ###
