"""ondelete_cascade

Revision ID: 066145f99d82
Revises: 5e1eb2164bac
Create Date: 2025-06-05 10:28:31.554988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "066145f99d82"
down_revision: Union[str, None] = "5e1eb2164bac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_receipt_items_receipt_id_receipts"),
        "receipt_items",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_receipt_items_receipt_id_receipts"),
        "receipt_items",
        "receipts",
        ["receipt_id"],
        ["receipt_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_receipt_items_receipt_id_receipts"),
        "receipt_items",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_receipt_items_receipt_id_receipts"),
        "receipt_items",
        "receipts",
        ["receipt_id"],
        ["receipt_id"],
    )
    # ### end Alembic commands ###
