"""init

Revision ID: f172863b9ae5
Revises:
Create Date: 2025-06-02 13:34:21.462153

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f172863b9ae5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receipts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("message_fiscal_sign", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("fiscal_drive_number", sa.String(length=16), nullable=False),
        sa.Column("kkt_reg_id", sa.String(length=20), nullable=False),
        sa.Column("user_inn", sa.String(length=12), nullable=False),
        sa.Column("fiscal_document_number", sa.Integer(), nullable=False),
        sa.Column("date_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("fiscal_sign", sa.Integer(), nullable=False),
        sa.Column("shift_number", sa.Integer(), nullable=False),
        sa.Column("request_number", sa.Integer(), nullable=False),
        sa.Column("operation_type", sa.Integer(), nullable=False),
        sa.Column("total_sum", sa.Integer(), nullable=False),
        sa.Column("fiscal_document_format_ver", sa.Integer(), nullable=False),
        sa.Column("buyer", sa.Text(), nullable=True),
        sa.Column("cash_total_sum", sa.Integer(), nullable=False),
        sa.Column("ecash_total_sum", sa.Integer(), nullable=False),
        sa.Column("prepaid_sum", sa.Integer(), nullable=False),
        sa.Column("credit_sum", sa.Integer(), nullable=False),
        sa.Column("provision_sum", sa.Integer(), nullable=False),
        sa.Column("nds_no", sa.Integer(), nullable=True),
        sa.Column("applied_taxation_type", sa.Integer(), nullable=True),
        sa.Column("operator", sa.Text(), nullable=True),
        sa.Column("operator_inn", sa.String(length=12), nullable=True),
        sa.Column("user", sa.Text(), nullable=True),
        sa.Column("retail_place", sa.Text(), nullable=True),
        sa.Column("region", sa.String(length=10), nullable=True),
        sa.Column("number_kkt", sa.String(length=20), nullable=True),
        sa.Column("redefine_mask", sa.Integer(), nullable=True),
        sa.Column("metadata_id", sa.BigInteger(), nullable=True),
        sa.Column("ofd_id", sa.String(length=10), nullable=True),
        sa.Column("receive_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("subtype", sa.String(length=20), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipts")),
        sa.UniqueConstraint(
            "fiscal_drive_number",
            "fiscal_document_number",
            "fiscal_sign",
            name="unique_fiscal_data",
        ),
    )
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("phone", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("telegram_id", name=op.f("pk_users")),
    )
    op.create_table(
        "receipt_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("receipt_id", sa.BigInteger(), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column(
            "quantity", sa.Numeric(precision=10, scale=3), nullable=False
        ),
        sa.Column("sum", sa.Integer(), nullable=False),
        sa.Column("nds", sa.Integer(), nullable=True),
        sa.Column("product_type", sa.Integer(), nullable=True),
        sa.Column("payment_type", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
            name=op.f("fk_receipt_items_receipt_id_receipts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_items")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("receipt_items")
    op.drop_table("users")
    op.drop_table("receipts")
    # ### end Alembic commands ###
